const products = [
  //Snack
  { name: "Chips Original", category: "Snack", rack: 1 },
  { name: "Choco Bar", category: "Snack", rack: 2 },
  { name: "Gummy Bears", category: "Snack", rack: 3 },
  { name: "Potato Crisps", category: "Snack", rack: 4 },
  { name: "Peanut Butter Cookies", category: "Snack", rack: 5 },
  { name: "Cheese Sticks", category: "Snack", rack: 6 },
  { name: "Chocolate Wafers", category: "Snack", rack: 7 },
  { name: "Popcorn Caramel", category: "Snack", rack: 8 },
  { name: "Rice Crackers", category: "Snack", rack: 9 },
  { name: "Fruit Candy", category: "Snack", rack: 10 },
  { name: "Seaweed Snacks", category: "Snack", rack: 11 },
  { name: "Pretzel Sticks", category: "Snack", rack: 12 },
  { name: "Banana Chips", category: "Snack", rack: 13 },
  { name: "Corn Chips", category: "Snack", rack: 14 },
  { name: "Yogurt Bites", category: "Snack", rack: 15 },
  { name: "Oat Cookies", category: "Snack", rack: 16 },
  { name: "Chili Chips", category: "Snack", rack: 17 },
  { name: "Honey Almonds", category: "Snack", rack: 18 },
  { name: "Coconut Chips", category: "Snack", rack: 19 },
  { name: "Sweet Jelly", category: "Snack", rack: 20 },
  { name: "Chocolate Chip Cookies", category: "Snack", rack: 21 },
  { name: "Biscuit Sticks", category: "Snack", rack: 22 },
  { name: "Trail Mix", category: "Snack", rack: 23 },
  { name: "Granola Bars", category: "Snack", rack: 24 },
  { name: "Apple Chips", category: "Snack", rack: 25 },
  { name: "Cinnamon Pretzels", category: "Snack", rack: 26 },
  { name: "Spicy Peanuts", category: "Snack", rack: 27 },
  { name: "Cashew Nuts", category: "Snack", rack: 28 },
  { name: "Sunflower Seeds", category: "Snack", rack: 29 },
  { name: "Dried Mango", category: "Snack", rack: 30 },
  { name: "Popcorn Salted", category: "Snack", rack: 31 },
  { name: "Rice Cakes", category: "Snack", rack: 32 },
  { name: "Choco Puffs", category: "Snack", rack: 33 },
  { name: "Fruit Gummy", category: "Snack", rack: 34 },
  { name: "Veggie Chips", category: "Snack", rack: 35 },
  { name: "Almond Joy", category: "Snack", rack: 36 },
  { name: "Pineapple Chips", category: "Snack", rack: 37 },
  { name: "Tortilla Chips", category: "Snack", rack: 38 },
  { name: "Chocolate Pretzels", category: "Snack", rack: 39 },
  { name: "Bacon Jerky", category: "Snack", rack: 40 },
  { name: "Fig Bars", category: "Snack", rack: 41 },
  { name: "Ginger Candies", category: "Snack", rack: 42 },
  { name: "Popcorn Butter", category: "Snack", rack: 43 },
  { name: "Beef Jerky", category: "Snack", rack: 44 },
  { name: "Crispy Onions", category: "Snack", rack: 45 },
  { name: "Mango Slices", category: "Snack", rack: 46 },
  { name: "Peanut M&Ms", category: "Snack", rack: 47 },
  { name: "Coconut Macaroons", category: "Snack", rack: 48 },
  { name: "Pistachios", category: "Snack", rack: 49 },
  { name: "Honey Roasted Cashews", category: "Snack", rack: 50 },
  { name: "Choco Brownie Bites", category: "Snack", rack: 51 },
  { name: "Cinnamon Crisps", category: "Snack", rack: 52 },
  { name: "Cheese Balls", category: "Snack", rack: 53 },
  { name: "Sour Candy Strips", category: "Snack", rack: 54 },
  { name: "Churro Chips", category: "Snack", rack: 55 },
  { name: "Granola Clusters", category: "Snack", rack: 56 },
  { name: "Wasabi Peas", category: "Snack", rack: 57 },
  { name: "Caramel Nuts", category: "Snack", rack: 58 },
  { name: "Popcorn Cheese", category: "Snack", rack: 59 },
  { name: "Roasted Chickpeas", category: "Snack", rack: 60 },
  { name: "Dried Pineapple", category: "Snack", rack: 61 },
  { name: "Apple Rings", category: "Snack", rack: 62 },
  { name: "Chocolate Pretzels", category: "Snack", rack: 63 },
  { name: "Spicy Jerky", category: "Snack", rack: 64 },
  { name: "Fruit Rollups", category: "Snack", rack: 65 },
  { name: "Rice Puff Sticks", category: "Snack", rack: 66 },
  { name: "Peanut Bars", category: "Snack", rack: 67 },
  { name: "Salted Almonds", category: "Snack", rack: 68 },
  { name: "Sugar Coated Cashews", category: "Snack", rack: 69 },
  { name: "Dark Chocolate Chips", category: "Snack", rack: 70 },
  { name: "Banana Bread Bites", category: "Snack", rack: 71 },
  { name: "Choco Granola", category: "Snack", rack: 72 },
  { name: "Sweet Plantain Chips", category: "Snack", rack: 73 },
  { name: "Peanut Caramel Clusters", category: "Snack", rack: 74 },
  { name: "Blueberry Wafers", category: "Snack", rack: 75 },
  { name: "Trail Nut Mix", category: "Snack", rack: 76 },
  { name: "Cheddar Popcorn", category: "Snack", rack: 77 },
  { name: "Maple Cashews", category: "Snack", rack: 78 },
  { name: "Raspberry Gummy Rings", category: "Snack", rack: 79 },
  { name: "Carrot Chips", category: "Snack", rack: 80 },
  { name: "Chocolate Truffle Bars", category: "Snack", rack: 81 },
  { name: "Peanut Butter Bites", category: "Snack", rack: 82 },
  { name: "Cheese Puffs", category: "Snack", rack: 83 },
  { name: "Coconut Cashew Crunch", category: "Snack", rack: 84 },
  { name: "Pineapple Wafers", category: "Snack", rack: 85 },
  { name: "Sweet Chili Popcorn", category: "Snack", rack: 86 },
  { name: "Almond Biscotti", category: "Snack", rack: 87 },
  { name: "Honey Nut Bars", category: "Snack", rack: 88 },
  { name: "Pumpkin Seeds", category: "Snack", rack: 89 },
  { name: "Sour Apple Gummies", category: "Snack", rack: 90 },
  { name: "Dark Choco Almonds", category: "Snack", rack: 91 },
  { name: "Choco Hazelnut Spread", category: "Snack", rack: 92 },
  { name: "Ginger Snap Cookies", category: "Snack", rack: 93 },
  { name: "Cranberry Oat Bars", category: "Snack", rack: 94 },
  { name: "Peanut Butter Pretzels", category: "Snack", rack: 95 },
  { name: "Mini Cupcakes", category: "Snack", rack: 96 },
  { name: "Cheddar Crackers", category: "Snack", rack: 97 },
  { name: "Toffee Almond Crunch", category: "Snack", rack: 98 },
  { name: "Raisin Mix", category: "Snack", rack: 99 },
  { name: "Strawberry Yogurt Bites", category: "Snack", rack: 100 },
  { name: "Chocolate Coconut Bites", category: "Snack", rack: 101 },
  { name: "Honey Graham Crackers", category: "Snack", rack: 102 },
  { name: "Peanut Butter Fudge", category: "Snack", rack: 103 },
  { name: "Cinnamon Sugar Tortilla Chips", category: "Snack", rack: 104 },
  { name: "Chocolate Covered Raisins", category: "Snack", rack: 105 },
  { name: "Buffalo Cauliflower Bites", category: "Snack", rack: 106 },
  { name: "Maple Pecan Clusters", category: "Snack", rack: 107 },
  { name: "Coconut Chips", category: "Snack", rack: 108 },
  { name: "Honey Mustard Pretzels", category: "Snack", rack: 109 },
  { name: "Peanut Butter Filled Pretzels", category: "Snack", rack: 110 },
  { name: "Chocolate Dipped Almonds", category: "Snack", rack: 111 },
  { name: "Savory Snack Mix", category: "Snack", rack: 112 },
  { name: "Crispy Rice Treats", category: "Snack", rack: 113 },
  { name: "Peach Rings", category: "Snack", rack: 114 },
  { name: "Chocolate Mint Cookies", category: "Snack", rack: 115 },
  { name: "Honey Roasted Peanuts", category: "Snack", rack: 116 },
  { name: "Caramel Corn", category: "Snack", rack: 117 },
  { name: "Chocolate Covered Pretzels", category: "Snack", rack: 118 },
  { name: "Fruit and Nut Bars", category: "Snack", rack: 119 },
  { name: "Spicy Trail Mix", category: "Snack", rack: 120 },
  { name: "Coconut Cream Cookies", category: "Snack", rack: 121 },
  { name: "Chocolate Hazelnut Cookies", category: "Snack", rack: 122 },
  { name: "Almond Butter Cups", category: "Snack", rack: 123 },
  { name: "Peanut Butter Chocolate Bars", category: "Snack", rack: 124 },
  { name: "Cinnamon Apple Chips", category: "Snack", rack: 125 },
  { name: "Chocolate Chip Granola", category: "Snack", rack: 126 },
  { name: "Honey Roasted Sunflower Seeds", category: "Snack", rack: 127 },
  { name: "Fruit and Yogurt Parfaits", category: "Snack", rack: 128 },
  { name: "Chocolate Coconut Almonds", category: "Snack", rack: 129 },
  { name: "Savory Cheese Crisps", category: "Snack", rack: 130 },
  { name: "Peanut Butter Banana Chips", category: "Snack", rack: 131 },
  { name: "Chocolate Chip Muffins", category: "Snack", rack: 132 },
  { name: "Spicy Chickpeas", category: "Snack", rack: 133 },
  { name: "Honey Almond Granola", category: "Snack", rack: 134 },
  { name: "Chocolate Covered Coconut", category: "Snack", rack: 135 },
  { name: "Peanut Butter Rice Cakes", category: "Snack", rack: 136 },
  { name: "Cinnamon Roll Bites", category: "Snack", rack: 137 },
  { name: "Chocolate Peanut Butter Cups", category: "Snack", rack: 138 },
  { name: "Fruit and Nut Trail Mix", category: "Snack", rack: 139 },
  { name: "Honey Roasted Almonds", category: "Snack", rack: 140 },
  { name: "Chocolate Chip Cookies with Nuts", category: "Snack", rack: 141 },
  { name: "Savory Popcorn", category: "Snack", rack: 142 },
  { name: "Peanut Butter Chocolate Chip Bars", category: "Snack", rack: 143 },
  { name: "Coconut Almond Bites", category: "Snack", rack: 144 },
  { name: "Chocolate Dipped Fruit", category: "Snack", rack: 145 },
  { name: "Spicy Cheese Puffs", category: "Snack", rack: 146 },
  { name: "Honey Nut Cheerios", category: "Snack", rack: 147 },
  { name: "Chocolate Chip Pancakes", category: "Snack", rack: 148 },
  { name: "Fruit and Nut Energy Bites", category: "Snack", rack: 149 },
  { name: "Peanut Butter Chocolate Pretzels", category: "Snack", rack: 150 },
  { name: "Cinnamon Sugar Almonds", category: "Snack", rack: 151 },
  { name: "Chocolate Covered Strawberries", category: "Snack", rack: 152 },
  { name: "Savory Nut Mix", category: "Snack", rack: 153 },
  { name: "Peanut Butter and Jelly Bars", category: "Snack", rack: 154 },
  { name: "Coconut Macadamia Cookies", category: "Snack", rack: 155 },
  { name: "Chocolate Chip Energy Bites", category: "Snack", rack: 156 },
  { name: "Honey Roasted Cashew Clusters", category: "Snack", rack: 157 },
  { name: "Fruit and Nut Granola", category: "Snack", rack: 158 },
  { name: "Chocolate Almond Butter Cups", category: "Snack", rack: 159 },
  { name: "Spicy Honey Roasted Peanuts", category: "Snack", rack: 160 },
  { name: "Cinnamon Raisin Granola", category: "Snack", rack: 161 },
  {
    name: "Chocolate Peanut Butter Granola Bars",
    category: "Snack",
    rack: 162,
  },
  {
    name: "Peanut Butter Chocolate Chip Cookies",
    category: "Snack",
    rack: 163,
  },
  { name: "Coconut Lime Energy Bites", category: "Snack", rack: 164 },
  { name: "Chocolate Covered Almonds", category: "Snack", rack: 165 },
  { name: "Savory Cheese and Nut Mix", category: "Snack", rack: 166 },
  {
    name: "Peanut Butter and Banana Smoothie Bites",
    category: "Snack",
    rack: 167,
  },
  { name: "Cinnamon Sugar Pita Chips", category: "Snack", rack: 168 },
  { name: "Chocolate Chip Cookie Dough Bites", category: "Snack", rack: 169 },
  { name: "Honey Roasted Mixed Nuts", category: "Snack", rack: 170 },
  { name: "Fruit and Nut Snack Bars", category: "Snack", rack: 171 },
  { name: "Chocolate Hazelnut Granola", category: "Snack", rack: 172 },
  {
    name: "Peanut Butter and Chocolate Rice Cakes",
    category: "Snack",
    rack: 173,
  },
  { name: "Coconut Chocolate Chip Cookies", category: "Snack", rack: 174 },
  { name: "Savory Herb Popcorn", category: "Snack", rack: 175 },
  {
    name: "Peanut Butter and Jelly Energy Bites",
    category: "Snack",
    rack: 176,
  },
  { name: "Cinnamon Apple Granola", category: "Snack", rack: 177 },
  { name: "Chocolate Chip Protein Bars", category: "Snack", rack: 178 },
  { name: "Honey Almond Snack Mix", category: "Snack", rack: 179 },
  { name: "Fruit and Nut Clusters", category: "Snack", rack: 180 },
  { name: "Chocolate Coconut Protein Bites", category: "Snack", rack: 181 },
  {
    name: "Peanut Butter and Chocolate Pretzel Bites",
    category: "Snack",
    rack: 182,
  },
  { name: "Cinnamon Sugar Popcorn", category: "Snack", rack: 183 },
  {
    name: "Chocolate Chip Cookie Dough Protein Bars",
    category: "Snack",
    rack: 184,
  },
  { name: "Honey Roasted Pecan Clusters", category: "Snack", rack: 185 },
  { name: "Fruit and Nut Trail Bars", category: "Snack", rack: 186 },
  { name: "Chocolate Almond Protein Bites", category: "Snack", rack: 187 },
  { name: "Savory Cheese and Pretzel Mix", category: "Snack", rack: 188 },
  {
    name: "Peanut Butter and Banana Granola Bars",
    category: "Snack",
    rack: 189,
  },
  { name: "Cinnamon Raisin Protein Bites", category: "Snack", rack: 190 },
  { name: "Chocolate Chip Oatmeal Cookies", category: "Snack", rack: 191 },
  { name: "Honey Roasted Almond Snack Mix", category: "Snack", rack: 192 },
  { name: "Fruit and Nut Energy Bars", category: "Snack", rack: 193 },
  { name: "Chocolate Coconut Granola", category: "Snack", rack: 194 },
  {
    name: "Peanut Butter and Chocolate Snack Bars",
    category: "Snack",
    rack: 195,
  },
  { name: "Cinnamon Sugar Granola", category: "Snack", rack: 196 },
  { name: "Chocolate Chip Brownie Bites", category: "Snack", rack: 197 },
  { name: "Honey Roasted Trail Mix", category: "Snack", rack: 198 },
  { name: "Fruit and Nut Crunch Bars", category: "Snack", rack: 199 },
  { name: "Chocolate Almond Granola Bars", category: "Snack", rack: 200 },
  { name: "Savory Nut and Cheese Mix", category: "Snack", rack: 201 },
  { name: "Peanut Butter and Jelly Snack Bites", category: "Snack", rack: 202 },
  { name: "Cinnamon Apple Protein Bars", category: "Snack", rack: 203 },
  { name: "Chocolate Chip Snack Mix", category: "Snack", rack: 204 },
  { name: "Honey Roasted Cashew Snack Bars", category: "Snack", rack: 205 },
  { name: "Fruit and Nut Protein Bites", category: "Snack", rack: 206 },
  { name: "Chocolate Coconut Energy Bites", category: "Snack", rack: 207 },
  { name: "Peanut Butter and Chocolate Granola", category: "Snack", rack: 208 },
  { name: "Cinnamon Sugar Energy Bites", category: "Snack", rack: 209 },
  { name: "Chocolate Chip Cookie Bites", category: "Snack", rack: 210 },
  { name: "Honey Roasted Nut Clusters", category: "Snack", rack: 211 },
  { name: "Fruit and Nut Snack Mix", category: "Snack", rack: 212 },
  { name: "Chocolate Almond Snack Bars", category: "Snack", rack: 213 },
  { name: "Savory Cheese and Nut Bars", category: "Snack", rack: 214 },
  {
    name: "Peanut Butter and Banana Snack Bites",
    category: "Snack",
    rack: 215,
  },
  { name: "Cinnamon Raisin Snack Bars", category: "Snack", rack: 216 },
  { name: "Chocolate Chip Oat Bars", category: "Snack", rack: 217 },
  { name: "Honey Roasted Almond Protein Bites", category: "Snack", rack: 218 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 219 },
  { name: "Chocolate Coconut Protein Bars", category: "Snack", rack: 220 },
  {
    name: "Peanut Butter and Chocolate Crunch Bars",
    category: "Snack",
    rack: 221,
  },
  { name: "Cinnamon Sugar Protein Bars", category: "Snack", rack: 222 },
  {
    name: "Chocolate Chip Brownie Protein Bites",
    category: "Snack",
    rack: 223,
  },
  { name: "Honey Roasted Trail Bars", category: "Snack", rack: 224 },
  { name: "Fruit and Nut Energy Mix", category: "Snack", rack: 225 },
  { name: "Chocolate Almond Crunch Bars", category: "Snack", rack: 226 },
  { name: "Savory Nut and Cheese Bars", category: "Snack", rack: 227 },
  {
    name: "Peanut Butter and Jelly Crunch Bites",
    category: "Snack",
    rack: 228,
  },
  { name: "Cinnamon Apple Snack Mix", category: "Snack", rack: 229 },
  { name: "Chocolate Chip Snack Bars", category: "Snack", rack: 230 },
  { name: "Honey Roasted Cashew Crunch Bars", category: "Snack", rack: 231 },
  { name: "Fruit and Nut Protein Bars", category: "Snack", rack: 232 },
  { name: "Chocolate Coconut Snack Bites", category: "Snack", rack: 233 },
  {
    name: "Peanut Butter and Chocolate Snack Mix",
    category: "Snack",
    rack: 234,
  },
  { name: "Cinnamon Sugar Snack Bars", category: "Snack", rack: 235 },
  { name: "Chocolate Chip Cookie Protein Bars", category: "Snack", rack: 236 },
  { name: "Honey Roasted Nut Energy Bites", category: "Snack", rack: 237 },
  { name: "Fruit and Nut Crunch Bars", category: "Snack", rack: 238 },
  { name: "Chocolate Almond Energy Bites", category: "Snack", rack: 239 },
  { name: "Savory Nut and Cheese Crunch", category: "Snack", rack: 240 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 241,
  },
  { name: "Cinnamon Raisin Snack Mix", category: "Snack", rack: 242 },
  {
    name: "Chocolate Chip Oatmeal Protein Bites",
    category: "Snack",
    rack: 243,
  },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 244 },
  { name: "Fruit and Nut Snack Bars", category: "Snack", rack: 245 },
  { name: "Chocolate Coconut Crunch Bars", category: "Snack", rack: 246 },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 247,
  },
  { name: "Cinnamon Sugar Oat Bars", category: "Snack", rack: 248 },
  { name: "Chocolate Chip Brownie Crunch Bites", category: "Snack", rack: 249 },
  { name: "Honey Roasted Trail Mix Bars", category: "Snack", rack: 250 },
  { name: "Fruit and Nut Energy Crunch", category: "Snack", rack: 251 },
  { name: "Chocolate Almond Snack Mix", category: "Snack", rack: 252 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 253 },
  { name: "Peanut Butter and Jelly Crunch Mix", category: "Snack", rack: 254 },
  { name: "Cinnamon Apple Crunch Bars", category: "Snack", rack: 255 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 256 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 257 },
  { name: "Fruit and Nut Protein Crunch", category: "Snack", rack: 258 },
  { name: "Chocolate Coconut Snack Mix", category: "Snack", rack: 259 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 260,
  },
  { name: "Cinnamon Sugar Protein Crunch Bars", category: "Snack", rack: 261 },
  { name: "Chocolate Chip Cookie Crunch Bites", category: "Snack", rack: 262 },
  { name: "Honey Roasted Nut Crunch Bars", category: "Snack", rack: 263 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 264 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 265 },
  { name: "Savory Nut and Cheese Protein Bites", category: "Snack", rack: 266 },
  { name: "Peanut Butter and Banana Crunch Mix", category: "Snack", rack: 267 },
  { name: "Cinnamon Raisin Crunch Bars", category: "Snack", rack: 268 },
  { name: "Chocolate Chip Oatmeal Crunch Bites", category: "Snack", rack: 269 },
  { name: "Honey Roasted Almond Crunch Bars", category: "Snack", rack: 270 },
  { name: "Fruit and Nut Snack Crunch", category: "Snack", rack: 271 },
  { name: "Chocolate Coconut Crunch Mix", category: "Snack", rack: 272 },
  {
    name: "Peanut Butter and Chocolate Crunch Bars",
    category: "Snack",
    rack: 273,
  },
  { name: "Cinnamon Sugar Oat Crunch Bars", category: "Snack", rack: 274 },
  { name: "Chocolate Chip Brownie Crunch Bars", category: "Snack", rack: 275 },
  { name: "Honey Roasted Trail Mix Crunch", category: "Snack", rack: 276 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 277 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 278 },
  { name: "Savory Nut and Cheese Crunch Mix", category: "Snack", rack: 279 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 280 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 281 },
  { name: "Chocolate Chip Snack Crunch Bites", category: "Snack", rack: 282 },
  { name: "Honey Roasted Cashew Crunch Bars", category: "Snack", rack: 283 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 284 },
  { name: "Chocolate Coconut Snack Crunch", category: "Snack", rack: 285 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 286,
  },
  { name: "Cinnamon Sugar Protein Crunch Bites", category: "Snack", rack: 287 },
  { name: "Chocolate Chip Cookie Crunch Mix", category: "Snack", rack: 288 },
  { name: "Honey Roasted Nut Crunch Mix", category: "Snack", rack: 289 },
  { name: "Fruit and Nut Crunch Bars", category: "Snack", rack: 290 },
  { name: "Chocolate Almond Energy Crunch Mix", category: "Snack", rack: 291 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 292 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 293,
  },
  { name: "Cinnamon Raisin Crunch Mix", category: "Snack", rack: 294 },
  { name: "Chocolate Chip Oatmeal Crunch Bars", category: "Snack", rack: 295 },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 296 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 297 },
  { name: "Chocolate Coconut Crunch Bars", category: "Snack", rack: 298 },
  {
    name: "Peanut Butter and Chocolate Snack Crunch",
    category: "Snack",
    rack: 299,
  },
  { name: "Cinnamon Sugar Oat Crunch Mix", category: "Snack", rack: 300 },
  { name: "Chocolate Almond Butter Cups", category: "Snack", rack: 301 },
  { name: "Savory Cheese and Nut Mix", category: "Snack", rack: 302 },
  {
    name: "Peanut Butter and Banana Smoothie Bites",
    category: "Snack",
    rack: 303,
  },
  { name: "Cinnamon Sugar Pita Chips", category: "Snack", rack: 304 },
  { name: "Chocolate Chip Cookie Dough Bites", category: "Snack", rack: 305 },
  { name: "Honey Roasted Mixed Nuts", category: "Snack", rack: 306 },
  { name: "Fruit and Nut Snack Bars", category: "Snack", rack: 307 },
  { name: "Chocolate Hazelnut Granola", category: "Snack", rack: 308 },
  {
    name: "Peanut Butter and Chocolate Rice Cakes",
    category: "Snack",
    rack: 309,
  },
  { name: "Coconut Chocolate Chip Cookies", category: "Snack", rack: 310 },
  { name: "Savory Herb Popcorn", category: "Snack", rack: 311 },
  {
    name: "Peanut Butter and Jelly Energy Bites",
    category: "Snack",
    rack: 312,
  },
  { name: "Cinnamon Apple Granola", category: "Snack", rack: 313 },
  { name: "Chocolate Chip Protein Bars", category: "Snack", rack: 314 },
  { name: "Honey Almond Snack Mix", category: "Snack", rack: 315 },
  { name: "Fruit and Nut Clusters", category: "Snack", rack: 316 },
  { name: "Chocolate Coconut Protein Bites", category: "Snack", rack: 317 },
  {
    name: "Peanut Butter and Chocolate Pretzel Bites",
    category: "Snack",
    rack: 318,
  },
  { name: "Cinnamon Sugar Popcorn", category: "Snack", rack: 319 },
  {
    name: "Chocolate Chip Cookie Dough Protein Bars",
    category: "Snack",
    rack: 320,
  },
  { name: "Honey Roasted Pecan Clusters", category: "Snack", rack: 321 },
  { name: "Fruit and Nut Trail Bars", category: "Snack", rack: 322 },
  { name: "Chocolate Almond Protein Bites", category: "Snack", rack: 323 },
  { name: "Savory Cheese and Pretzel Mix", category: "Snack", rack: 324 },
  {
    name: "Peanut Butter and Banana Granola Bars",
    category: "Snack",
    rack: 325,
  },
  { name: "Cinnamon Raisin Protein Bites", category: "Snack", rack: 326 },
  { name: "Chocolate Chip Oatmeal Cookies", category: "Snack", rack: 327 },
  { name: "Honey Roasted Almond Snack Mix", category: "Snack", rack: 328 },
  { name: "Fruit and Nut Energy Bars", category: "Snack", rack: 329 },
  { name: "Chocolate Coconut Granola", category: "Snack", rack: 330 },
  {
    name: "Peanut Butter and Chocolate Snack Bars",
    category: "Snack",
    rack: 331,
  },
  { name: "Cinnamon Sugar Granola", category: "Snack", rack: 332 },
  { name: "Chocolate Chip Brownie Bites", category: "Snack", rack: 333 },
  { name: "Honey Roasted Trail Mix", category: "Snack", rack: 334 },
  { name: "Fruit and Nut Crunch Bars", category: "Snack", rack: 335 },
  { name: "Chocolate Almond Granola Bars", category: "Snack", rack: 336 },
  { name: "Savory Nut and Cheese Mix", category: "Snack", rack: 337 },
  { name: "Peanut Butter and Jelly Snack Bites", category: "Snack", rack: 338 },
  { name: "Cinnamon Apple Protein Bars", category: "Snack", rack: 339 },
  { name: "Chocolate Chip Snack Mix", category: "Snack", rack: 340 },
  { name: "Honey Roasted Cashew Snack Bars", category: "Snack", rack: 341 },
  { name: "Fruit and Nut Protein Bites", category: "Snack", rack: 342 },
  { name: "Chocolate Coconut Energy Bites", category: "Snack", rack: 343 },
  {
    name: "Peanut Butter and Chocolate Crunch Bars",
    category: "Snack",
    rack: 344,
  },
  { name: "Cinnamon Sugar Protein Bars", category: "Snack", rack: 345 },
  {
    name: "Chocolate Chip Brownie Protein Bites",
    category: "Snack",
    rack: 346,
  },
  { name: "Honey Roasted Trail Bars", category: "Snack", rack: 347 },
  { name: "Fruit and Nut Energy Crunch", category: "Snack", rack: 348 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 349 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 350 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 351,
  },
  { name: "Cinnamon Raisin Crunch Mix", category: "Snack", rack: 352 },
  { name: "Chocolate Chip Oatmeal Crunch Bars", category: "Snack", rack: 353 },
  { name: "Honey Roasted Almond Crunch Bars", category: "Snack", rack: 354 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 355 },
  { name: "Chocolate Coconut Crunch Bars", category: "Snack", rack: 356 },
  {
    name: "Peanut Butter and Chocolate Snack Crunch",
    category: "Snack",
    rack: 357,
  },
  { name: "Cinnamon Sugar Oat Crunch Bars", category: "Snack", rack: 358 },
  { name: "Chocolate Chip Brownie Crunch Bars", category: "Snack", rack: 359 },
  { name: "Honey Roasted Trail Mix Crunch", category: "Snack", rack: 360 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 361 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 362 },
  { name: "Savory Nut and Cheese Protein Bites", category: "Snack", rack: 363 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 364 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 365 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 366 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 367 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 368 },
  { name: "Chocolate Coconut Snack Crunch", category: "Snack", rack: 369 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 370,
  },
  { name: "Cinnamon Sugar Protein Crunch Bites", category: "Snack", rack: 371 },
  { name: "Chocolate Chip Cookie Crunch Bites", category: "Snack", rack: 372 },
  { name: "Honey Roasted Nut Crunch Bars", category: "Snack", rack: 373 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 374 },
  { name: "Chocolate Almond Energy Crunch Mix", category: "Snack", rack: 375 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 376 },
  { name: "Peanut Butter and Banana Crunch Mix", category: "Snack", rack: 377 },
  { name: "Cinnamon Raisin Crunch Bars", category: "Snack", rack: 378 },
  { name: "Chocolate Chip Oatmeal Crunch Bites", category: "Snack", rack: 379 },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 380 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 381 },
  { name: "Chocolate Coconut Crunch Mix", category: "Snack", rack: 382 },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 383,
  },
  { name: "Cinnamon Sugar Oat Crunch Mix", category: "Snack", rack: 384 },
  { name: "Chocolate Chip Brownie Crunch Bites", category: "Snack", rack: 385 },
  { name: "Honey Roasted Trail Mix Bars", category: "Snack", rack: 386 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 387 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 388 },
  { name: "Savory Nut and Cheese Crunch Mix", category: "Snack", rack: 389 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 390 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 391 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 392 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 393 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 394 },
  { name: "Chocolate Coconut Snack Crunch", category: "Snack", rack: 395 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 396,
  },
  { name: "Cinnamon Sugar Protein Crunch Bites", category: "Snack", rack: 397 },
  { name: "Chocolate Chip Cookie Crunch Bites", category: "Snack", rack: 398 },
  { name: "Honey Roasted Nut Crunch Bars", category: "Snack", rack: 399 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 400 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 401 },
  { name: "Savory Nut and Cheese Protein Bites", category: "Snack", rack: 402 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 403,
  },
  { name: "Cinnamon Raisin Crunch Bars", category: "Snack", rack: 404 },
  { name: "Chocolate Chip Oatmeal Crunch Bars", category: "Snack", rack: 405 },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 406 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 407 },
  { name: "Chocolate Coconut Crunch Mix", category: "Snack", rack: 408 },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 409,
  },
  { name: "Cinnamon Sugar Oat Crunch Mix", category: "Snack", rack: 410 },
  { name: "Chocolate Chip Brownie Crunch Bites", category: "Snack", rack: 411 },
  { name: "Honey Roasted Trail Mix Bars", category: "Snack", rack: 412 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 413 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 414 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 415 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 416 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 417 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 418 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 419 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 420 },
  { name: "Chocolate Coconut Snack Crunch", category: "Snack", rack: 421 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 422,
  },
  { name: "Cinnamon Sugar Protein Crunch Bites", category: "Snack", rack: 423 },
  { name: "Chocolate Chip Cookie Crunch Bites", category: "Snack", rack: 424 },
  { name: "Honey Roasted Nut Crunch Bars", category: "Snack", rack: 425 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 426 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 427 },
  { name: "Savory Nut and Cheese Protein Bites", category: "Snack", rack: 428 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 429,
  },
  { name: "Cinnamon Raisin Crunch Bars", category: "Snack", rack: 430 },
  { name: "Chocolate Chip Oatmeal Crunch Bars", category: "Snack", rack: 431 },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 432 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 433 },
  { name: "Chocolate Coconut Crunch Mix", category: "Snack", rack: 434 },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 435,
  },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 436,
  },
  { name: "Cinnamon Sugar Oat Crunch Mix", category: "Snack", rack: 437 },
  { name: "Chocolate Chip Brownie Crunch Bites", category: "Snack", rack: 438 },
  { name: "Honey Roasted Trail Mix Bars", category: "Snack", rack: 439 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 440 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 441 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 442 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 443 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 444 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 445 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 446 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 447 },
  { name: "Chocolate Coconut Snack Crunch", category: "Snack", rack: 448 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 449,
  },
  { name: "Cinnamon Sugar Protein Crunch Bites", category: "Snack", rack: 450 },
  { name: "Chocolate Chip Cookie Crunch Bites", category: "Snack", rack: 451 },
  { name: "Honey Roasted Nut Crunch Bars", category: "Snack", rack: 452 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 453 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 454 },
  { name: "Savory Nut and Cheese Protein Bites", category: "Snack", rack: 455 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 456,
  },
  { name: "Cinnamon Raisin Crunch Bars", category: "Snack", rack: 457 },
  { name: "Chocolate Chip Oatmeal Crunch Bars", category: "Snack", rack: 458 },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 459 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 460 },
  { name: "Chocolate Coconut Crunch Mix", category: "Snack", rack: 461 },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 462,
  },
  { name: "Cinnamon Sugar Oat Crunch Mix", category: "Snack", rack: 463 },
  { name: "Chocolate Chip Brownie Crunch Bites", category: "Snack", rack: 464 },
  { name: "Honey Roasted Trail Mix Bars", category: "Snack", rack: 465 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 466 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 467 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 468 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 469 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 470 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 471 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 472 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 473 },
  { name: "Chocolate Coconut Snack Crunch", category: "Snack", rack: 474 },
  {
    name: "Peanut Butter and Chocolate Crunch Mix",
    category: "Snack",
    rack: 475,
  },
  { name: "Cinnamon Sugar Protein Crunch Bites", category: "Snack", rack: 476 },
  { name: "Chocolate Chip Cookie Crunch Bites", category: "Snack", rack: 477 },
  { name: "Honey Roasted Nut Crunch Bars", category: "Snack", rack: 478 },
  { name: "Fruit and Nut Crunch Mix", category: "Snack", rack: 479 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 480 },
  { name: "Chocolate Almond Energy Crunch Bars", category: "Snack", rack: 481 },
  { name: "Savory Nut and Cheese Protein Bites", category: "Snack", rack: 482 },
  {
    name: "Peanut Butter and Banana Crunch Bars",
    category: "Snack",
    rack: 483,
  },
  { name: "Cinnamon Raisin Crunch Bars", category: "Snack", rack: 484 },
  { name: "Chocolate Chip Oatmeal Crunch Bars", category: "Snack", rack: 485 },
  { name: "Honey Roasted Almond Crunch Mix", category: "Snack", rack: 486 },
  { name: "Fruit and Nut Snack Crunch Bars", category: "Snack", rack: 487 },
  { name: "Chocolate Coconut Crunch Mix", category: "Snack", rack: 488 },
  {
    name: "Peanut Butter and Chocolate Snack Bites",
    category: "Snack",
    rack: 489,
  },
  { name: "Cinnamon Sugar Oat Crunch Mix", category: "Snack", rack: 490 },
  { name: "Chocolate Chip Brownie Crunch Bites", category: "Snack", rack: 491 },
  { name: "Honey Roasted Trail Mix Bars", category: "Snack", rack: 492 },
  { name: "Fruit and Nut Energy Crunch Bars", category: "Snack", rack: 493 },
  { name: "Chocolate Almond Snack Crunch", category: "Snack", rack: 494 },
  { name: "Savory Nut and Cheese Crunch Bars", category: "Snack", rack: 495 },
  { name: "Peanut Butter and Jelly Crunch Bars", category: "Snack", rack: 496 },
  { name: "Cinnamon Apple Crunch Mix", category: "Snack", rack: 497 },
  { name: "Chocolate Chip Snack Bites", category: "Snack", rack: 498 },
  { name: "Honey Roasted Cashew Crunch Mix", category: "Snack", rack: 499 },
  { name: "Fruit and Nut Protein Crunch Bars", category: "Snack", rack: 500 },
  // Alat Mandi
  { name: "Shampoo Herbal", category: "Alat Mandi", rack: 1 },
  { name: "Body Wash Citrus", category: "Alat Mandi", rack: 2 },
  { name: "Toothpaste Mint", category: "Alat Mandi", rack: 3 },
  { name: "Hand Soap", category: "Alat Mandi", rack: 4 },
  { name: "Bath Towel", category: "Alat Mandi", rack: 5 },
  { name: "Face Wash", category: "Alat Mandi", rack: 6 },
  { name: "Hair Conditioner", category: "Alat Mandi", rack: 7 },
  { name: "Mouthwash", category: "Alat Mandi", rack: 8 },
  { name: "Body Lotion", category: "Alat Mandi", rack: 9 },
  { name: "Deodorant Roll-On", category: "Alat Mandi", rack: 10 },
  { name: "Shaving Cream", category: "Alat Mandi", rack: 11 },
  { name: "Toothbrush Soft", category: "Alat Mandi", rack: 12 },
  { name: "Bath Sponge", category: "Alat Mandi", rack: 13 },
  { name: "Baby Powder", category: "Alat Mandi", rack: 14 },
  { name: "Hair Gel", category: "Alat Mandi", rack: 15 },
  { name: "Body Scrub", category: "Alat Mandi", rack: 16 },
  { name: "Shower Cap", category: "Alat Mandi", rack: 17 },
  { name: "Lip Balm", category: "Alat Mandi", rack: 18 },
  { name: "Wet Wipes", category: "Alat Mandi", rack: 19 },
  { name: "Cotton Swabs", category: "Alat Mandi", rack: 20 },
  { name: "Hand Cream", category: "Alat Mandi", rack: 21 },
  { name: "Foot Cream", category: "Alat Mandi", rack: 22 },
  { name: "Shaving Razor", category: "Alat Mandi", rack: 23 },
  { name: "Facial Tissues", category: "Alat Mandi", rack: 24 },
  { name: "Nail Clippers", category: "Alat Mandi", rack: 25 },
  { name: "Bathe Mitt", category: "Alat Mandi", rack: 26 },
  { name: "Eye Mask", category: "Alat Mandi", rack: 27 },
  { name: "Toothbrush Holder", category: "Alat Mandi", rack: 28 },
  { name: "Shampoo Bar", category: "Alat Mandi", rack: 29 },
  { name: "Bubble Bath", category: "Alat Mandi", rack: 30 },
  { name: "Cleansing Oil", category: "Alat Mandi", rack: 31 },
  { name: "Facial Toner", category: "Alat Mandi", rack: 32 },
  { name: "Moisturizing Cream", category: "Alat Mandi", rack: 33 },
  { name: "Antiseptic Cream", category: "Alat Mandi", rack: 34 },
  { name: "Sunscreen", category: "Alat Mandi", rack: 35 },
  { name: "Lip Scrub", category: "Alat Mandi", rack: 36 },
  { name: "Shaving Gel", category: "Alat Mandi", rack: 37 },
  { name: "Face Mask", category: "Alat Mandi", rack: 38 },
  { name: "Tooth Whitening Kit", category: "Alat Mandi", rack: 39 },
  { name: "Ear Cleaner", category: "Alat Mandi", rack: 40 },
  { name: "Hand Sanitizer", category: "Alat Mandi", rack: 41 },
  { name: "Nail Polish Remover", category: "Alat Mandi", rack: 42 },
  { name: "Hair Serum", category: "Alat Mandi", rack: 43 },
  { name: "Foot Scrub", category: "Alat Mandi", rack: 44 },
  { name: "Hair Brush", category: "Alat Mandi", rack: 45 },
  { name: "Shower Gel", category: "Alat Mandi", rack: 46 },
  { name: "Toothpaste Whitening", category: "Alat Mandi", rack: 47 },
  { name: "Electric Toothbrush", category: "Alat Mandi", rack: 48 },
  { name: "Face Mask Sheet", category: "Alat Mandi", rack: 49 },
  { name: "Body Powder", category: "Alat Mandi", rack: 50 },
  { name: "Bubble Soap", category: "Alat Mandi", rack: 51 },
  { name: "Shampoo Lavender", category: "Alat Mandi", rack: 52 },
  { name: "Bath Crystals", category: "Alat Mandi", rack: 53 },
  { name: "Hair Mousse", category: "Alat Mandi", rack: 54 },
  { name: "Soap Dish", category: "Alat Mandi", rack: 55 },
  { name: "Scented Candles", category: "Alat Mandi", rack: 56 },
  { name: "Exfoliating Scrub", category: "Alat Mandi", rack: 57 },
  { name: "Shower Balm", category: "Alat Mandi", rack: 58 },
  { name: "Facial Cleanser", category: "Alat Mandi", rack: 59 },
  { name: "Tooth Cleaning Gel", category: "Alat Mandi", rack: 60 },
  { name: "Hair Volumizer", category: "Alat Mandi", rack: 61 },
  { name: "Bubble Maker", category: "Alat Mandi", rack: 62 },
  { name: "Foot Warmer", category: "Alat Mandi", rack: 63 },
  { name: "Moisturizer Balm", category: "Alat Mandi", rack: 64 },
  { name: "Body Wax", category: "Alat Mandi", rack: 65 },
  { name: "Hair Dye", category: "Alat Mandi", rack: 66 },
  { name: "Pumice Stone", category: "Alat Mandi", rack: 67 },
  { name: "Towel Wrap", category: "Alat Mandi", rack: 68 },
  { name: "Bathrobe", category: "Alat Mandi", rack: 69 },
  { name: "Razor Blade", category: "Alat Mandi", rack: 70 },
  { name: "Shampoo Foam", category: "Alat Mandi", rack: 71 },
  { name: "Body Polish", category: "Alat Mandi", rack: 72 },
  { name: "Face Serum", category: "Alat Mandi", rack: 73 },
  { name: "Nail File", category: "Alat Mandi", rack: 74 },
  { name: "Bath Caddy", category: "Alat Mandi", rack: 75 },
  { name: "Bath Fizz", category: "Alat Mandi", rack: 76 },
  { name: "Hair Curl Cream", category: "Alat Mandi", rack: 77 },
  { name: "Body Mist", category: "Alat Mandi", rack: 78 },
  { name: "Loofah", category: "Alat Mandi", rack: 79 },
  { name: "Face Oil", category: "Alat Mandi", rack: 80 },
  { name: "Bath Oil", category: "Alat Mandi", rack: 81 },
  { name: "Hair Mask", category: "Alat Mandi", rack: 82 },
  { name: "Makeup Remover", category: "Alat Mandi", rack: 83 },
  { name: "Shower Gloves", category: "Alat Mandi", rack: 84 },
  { name: "Toe Separator", category: "Alat Mandi", rack: 85 },
  { name: "Hair Clips", category: "Alat Mandi", rack: 86 },
  { name: "Body Exfoliator", category: "Alat Mandi", rack: 87 },
  { name: "Tooth Floss", category: "Alat Mandi", rack: 88 },
  { name: "Shampoo Pump", category: "Alat Mandi", rack: 89 },
  { name: "Foot Soak", category: "Alat Mandi", rack: 90 },
  { name: "Face Sponge", category: "Alat Mandi", rack: 91 },
  { name: "Body Spray", category: "Alat Mandi", rack: 92 },
  { name: "Shaving Cream Tube", category: "Alat Mandi", rack: 93 },
  { name: "Bath Gel", category: "Alat Mandi", rack: 94 },
  { name: "Eye Cream", category: "Alat Mandi", rack: 95 },
  { name: "Travel Towel", category: "Alat Mandi", rack: 96 },
  { name: "Hair Rinse", category: "Alat Mandi", rack: 97 },
  { name: "Soap Bar", category: "Alat Mandi", rack: 98 },
  { name: "Tooth Powder", category: "Alat Mandi", rack: 99 },
  { name: "Body Conditioner", category: "Alat Mandi", rack: 100 },
  { name: "Shower Oil", category: "Alat Mandi", rack: 101 },
  { name: "Facial Peeling Gel", category: "Alat Mandi", rack: 102 },
  { name: "Hair Repair Treatment", category: "Alat Mandi", rack: 103 },
  { name: "Body Shimmer", category: "Alat Mandi", rack: 104 },
  { name: "Nail Strengthener", category: "Alat Mandi", rack: 105 },
  { name: "Foot Peel Mask", category: "Alat Mandi", rack: 106 },
  { name: "Shower Mist", category: "Alat Mandi", rack: 107 },
  { name: "Facial Mist", category: "Alat Mandi", rack: 108 },
  { name: "Hair Frizz Control", category: "Alat Mandi", rack: 109 },
  { name: "Body Glow Oil", category: "Alat Mandi", rack: 110 },
  { name: "Exfoliating Foot Mask", category: "Alat Mandi", rack: 111 },
  { name: "Shower Jelly", category: "Alat Mandi", rack: 112 },
  { name: "Facial Exfoliator", category: "Alat Mandi", rack: 113 },
  { name: "Body Firming Cream", category: "Alat Mandi", rack: 114 },
  { name: "Hair Detangler", category: "Alat Mandi", rack: 115 },
  { name: "Bath Salts", category: "Alat Mandi", rack: 116 },
  { name: "Cooling Foot Spray", category: "Alat Mandi", rack: 117 },
  { name: "Shower Puffs", category: "Alat Mandi", rack: 118 },
  { name: "Facial Cleansing Brush", category: "Alat Mandi", rack: 119 },
  { name: "Body Shaving Gel", category: "Alat Mandi", rack: 120 },
  { name: "Hair Growth Serum", category: "Alat Mandi", rack: 121 },
  { name: "Bath Bombs", category: "Alat Mandi", rack: 122 },
  { name: "Body Shaving Cream", category: "Alat Mandi", rack: 123 },
  { name: "Facial Scrub", category: "Alat Mandi", rack: 124 },
  { name: "Hair Styling Mousse", category: "Alat Mandi", rack: 125 },
  { name: "Body Wash Foam", category: "Alat Mandi", rack: 126 },
  { name: "Shower Cream", category: "Alat Mandi", rack: 127 },
  { name: "Facial Cleansing Wipes", category: "Alat Mandi", rack: 128 },
  { name: "Body Shimmer Mist", category: "Alat Mandi", rack: 129 },
  { name: "Hair Curling Spray", category: "Alat Mandi", rack: 130 },
  { name: "Moisturizing Body Wash", category: "Alat Mandi", rack: 131 },
  { name: "Hydrating Face Mask", category: "Alat Mandi", rack: 132 },
  { name: "Nourishing Hair Oil", category: "Alat Mandi", rack: 133 },
  { name: "Body Butter", category: "Alat Mandi", rack: 134 },
  { name: "Foot Scrub Cream", category: "Alat Mandi", rack: 135 },
  { name: "Shower Gel with Aloe Vera", category: "Alat Mandi", rack: 136 },
  { name: "Facial Hydrating Mist", category: "Alat Mandi", rack: 137 },
  { name: "Hair Repair Serum", category: "Alat Mandi", rack: 138 },
  { name: "Body Wash with Charcoal", category: "Alat Mandi", rack: 139 },
  { name: "Exfoliating Body Wash", category: "Alat Mandi", rack: 140 },
  { name: "Cleansing Facial Wipes", category: "Alat Mandi", rack: 141 },
  { name: "Hair Styling Gel", category: "Alat Mandi", rack: 142 },
  { name: "Body Oil", category: "Alat Mandi", rack: 143 },
  { name: "Foot Cream with Menthol", category: "Alat Mandi", rack: 144 },
  { name: "Shower Gel with Coconut", category: "Alat Mandi", rack: 145 },
  { name: "Facial Brightening Serum", category: "Alat Mandi", rack: 146 },
  { name: "Hair Curl Definer", category: "Alat Mandi", rack: 147 },
  { name: "Body Wash with Honey", category: "Alat Mandi", rack: 148 },
  { name: "Exfoliating Facial Scrub", category: "Alat Mandi", rack: 149 },
  { name: "Hair Smoothing Cream", category: "Alat Mandi", rack: 150 },
  { name: "Body Wash with Lavender", category: "Alat Mandi", rack: 151 },
  { name: "Facial Moisturizing Cream", category: "Alat Mandi", rack: 152 },
  { name: "Hair Repair Mask", category: "Alat Mandi", rack: 153 },
  { name: "Body Wash with Tea Tree Oil", category: "Alat Mandi", rack: 154 },
  { name: "Facial Brightening Mask", category: "Alat Mandi", rack: 155 },
  { name: "Hair Volume Spray", category: "Alat Mandi", rack: 156 },
  { name: "Body Wash with Rose", category: "Alat Mandi", rack: 157 },
  { name: "Facial Firming Cream", category: "Alat Mandi", rack: 158 },
  { name: "Hair Repair Conditioner", category: "Alat Mandi", rack: 159 },
  { name: "Body Wash with Citrus", category: "Alat Mandi", rack: 160 },
  { name: "Facial Anti-Aging Serum", category: "Alat Mandi", rack: 161 },
  { name: "Hair Curl Activator", category: "Alat Mandi", rack: 162 },
  { name: "Body Wash with Mint", category: "Alat Mandi", rack: 163 },
  { name: "Facial Pore Minimizer", category: "Alat Mandi", rack: 164 },
  {
    name: "Hair Repair Leave-In Conditioner",
    category: "Alat Mandi",
    rack: 165,
  },
  { name: "Body Wash with Jasmine", category: "Alat Mandi", rack: 166 },
  { name: "Facial Oil Control Gel", category: "Alat Mandi", rack: 167 },
  { name: "Hair Frizz Control Cream", category: "Alat Mandi", rack: 168 },
  { name: "Body Wash with Olive Oil", category: "Alat Mandi", rack: 169 },
  { name: "Facial Skin Brightener", category: "Alat Mandi", rack: 170 },
  { name: "Hair Nourishing Cream", category: "Alat Mandi", rack: 171 },
  { name: "Body Wash with Almond Oil", category: "Alat Mandi", rack: 172 },
  { name: "Facial Skin Repair Cream", category: "Alat Mandi", rack: 173 },
  { name: "Hair Moisturizing Spray", category: "Alat Mandi", rack: 174 },
  { name: "Body Wash with Grapefruit", category: "Alat Mandi", rack: 175 },
  { name: "Facial Skin Soothing Gel", category: "Alat Mandi", rack: 176 },
  { name: "Hair Repair Shampoo", category: "Alat Mandi", rack: 177 },
  { name: "Body Wash with Chamomile", category: "Alat Mandi", rack: 178 },
  { name: "Facial Skin Hydrating Cream", category: "Alat Mandi", rack: 179 },
  { name: "Hair Smoothing Shampoo", category: "Alat Mandi", rack: 180 },
  { name: "Body Wash with Eucalyptus", category: "Alat Mandi", rack: 181 },
  { name: "Facial Skin Nourishing Oil", category: "Alat Mandi", rack: 182 },
  {
    name: "Hair Repair Conditioner with Argan Oil",
    category: "Alat Mandi",
    rack: 183,
  },
  { name: "Body Wash with Coconut Milk", category: "Alat Mandi", rack: 184 },
  { name: "Facial Skin Revitalizing Serum", category: "Alat Mandi", rack: 185 },
  {
    name: "Hair Repair Treatment with Keratin",
    category: "Alat Mandi",
    rack: 186,
  },
  { name: "Body Wash with Papaya", category: "Alat Mandi", rack: 187 },
  { name: "Facial Skin Rejuvenating Cream", category: "Alat Mandi", rack: 188 },
  { name: "Hair Moisturizing Conditioner", category: "Alat Mandi", rack: 189 },
  { name: "Body Wash with Pomegranate", category: "Alat Mandi", rack: 190 },
  { name: "Facial Skin Exfoliating Gel", category: "Alat Mandi", rack: 191 },
  {
    name: "Hair Repair Serum with Jojoba Oil",
    category: "Alat Mandi",
    rack: 192,
  },
  { name: "Body Wash with Cucumber", category: "Alat Mandi", rack: 193 },
  { name: "Facial Skin Brightening Lotion", category: "Alat Mandi", rack: 194 },
  {
    name: "Hair Curling Cream with Coconut",
    category: "Alat Mandi",
    rack: 195,
  },
  { name: "Body Wash with Blackberry", category: "Alat Mandi", rack: 196 },
  { name: "Facial Skin Firming Lotion", category: "Alat Mandi", rack: 197 },
  { name: "Hair Repair Mask with Avocado", category: "Alat Mandi", rack: 198 },
  { name: "Body Wash with Strawberry", category: "Alat Mandi", rack: 199 },
  { name: "Facial Skin Hydrating Lotion", category: "Alat Mandi", rack: 200 },
  { name: "Hair Nourishing Shampoo", category: "Alat Mandi", rack: 201 },
  { name: "Body Wash with Blueberry", category: "Alat Mandi", rack: 202 },
  { name: "Facial Skin Soothing Lotion", category: "Alat Mandi", rack: 203 },
  {
    name: "Hair Repair Conditioner with Coconut",
    category: "Alat Mandi",
    rack: 204,
  },
  { name: "Body Wash with Tangerine", category: "Alat Mandi", rack: 205 },
  { name: "Facial Skin Nourishing Cream", category: "Alat Mandi", rack: 206 },
  {
    name: "Hair Moisturizing Conditioner with Aloe Vera",
    category: "Alat Mandi",
    rack: 207,
  },
  { name: "Body Wash with Mint Leaf", category: "Alat Mandi", rack: 208 },
  {
    name: "Facial Skin Revitalizing Lotion",
    category: "Alat Mandi",
    rack: 209,
  },
  {
    name: "Hair Repair Shampoo with Olive Oil",
    category: "Alat Mandi",
    rack: 210,
  },
  { name: "Body Wash with Lemon", category: "Alat Mandi", rack: 211 },
  { name: "Facial Skin Anti-Aging Lotion", category: "Alat Mandi", rack: 212 },
  {
    name: "Hair Smoothing Conditioner with Shea Butter",
    category: "Alat Mandi",
    rack: 213,
  },
  { name: "Body Wash with Ginger", category: "Alat Mandi", rack: 214 },
  {
    name: "Facial Skin Rejuvenating Lotion",
    category: "Alat Mandi",
    rack: 215,
  },
  {
    name: "Hair Repair Treatment with Honey",
    category: "Alat Mandi",
    rack: 216,
  },
  { name: "Body Wash with Clove", category: "Alat Mandi", rack: 217 },
  { name: "Facial Skin Brightening Gel", category: "Alat Mandi", rack: 218 },
  { name: "Hair Curling Cream with Almond", category: "Alat Mandi", rack: 219 },
  { name: "Body Wash with Cardamom", category: "Alat Mandi", rack: 220 },
  { name: "Facial Skin Firming Gel", category: "Alat Mandi", rack: 221 },
  {
    name: "Hair Repair Serum with Coconut Milk",
    category: "Alat Mandi",
    rack: 222,
  },
  { name: "Body Wash with Basil", category: "Alat Mandi", rack: 223 },
  { name: "Facial Skin Hydrating Gel", category: "Alat Mandi", rack: 224 },
  {
    name: "Hair Nourishing Conditioner with Coconut",
    category: "Alat Mandi",
    rack: 225,
  },
  { name: "Body Wash with Rosemary", category: "Alat Mandi", rack: 226 },
  {
    name: "Facial Skin Soothing Gel with Aloe Vera",
    category: "Alat Mandi",
    rack: 227,
  },
  { name: "Hair Repair Shampoo with Honey", category: "Alat Mandi", rack: 228 },
  { name: "Body Wash with Thyme", category: "Alat Mandi", rack: 229 },
  { name: "Facial Skin Revitalizing Gel", category: "Alat Mandi", rack: 230 },
  {
    name: "Hair Moisturizing Cream with Coconut",
    category: "Alat Mandi",
    rack: 231,
  },
  { name: "Body Wash with Sage", category: "Alat Mandi", rack: 232 },
  { name: "Facial Skin Nourishing Gel", category: "Alat Mandi", rack: 233 },
  {
    name: "Hair Repair Conditioner with Honey",
    category: "Alat Mandi",
    rack: 234,
  },
  { name: "Body Wash with Mint Extract", category: "Alat Mandi", rack: 235 },
  {
    name: "Facial Skin Brightening Cream with Vitamin C",
    category: "Alat Mandi",
    rack: 236,
  },
  {
    name: "Hair Curling Gel with Aloe Vera",
    category: "Alat Mandi",
    rack: 237,
  },
  { name: "Body Wash with Lavender Oil", category: "Alat Mandi", rack: 238 },
  {
    name: "Facial Skin Firming Cream with Collagen",
    category: "Alat Mandi",
    rack: 239,
  },
  {
    name: "Hair Repair Treatment with Olive Oil",
    category: "Alat Mandi",
    rack: 240,
  },
  {
    name: "Body Wash with Chamomile Extract",
    category: "Alat Mandi",
    rack: 241,
  },
  {
    name: "Facial Skin Hydrating Cream with Hyaluronic Acid",
    category: "Alat Mandi",
    rack: 242,
  },
  {
    name: "Hair Smoothing Shampoo with Coconut Milk",
    category: "Alat Mandi",
    rack: 243,
  },
  { name: "Body Wash with Vanilla", category: "Alat Mandi", rack: 244 },
  {
    name: "Facial Skin Rejuvenating Gel with Retinol",
    category: "Alat Mandi",
    rack: 245,
  },
  {
    name: "Hair Repair Serum with Argan Oil",
    category: "Alat Mandi",
    rack: 246,
  },
  { name: "Body Wash with Coconut Oil", category: "Alat Mandi", rack: 247 },
  {
    name: "Facial Skin Brightening Lotion with Niacinamide",
    category: "Alat Mandi",
    rack: 248,
  },
  {
    name: "Hair Curling Cream with Jojoba Oil",
    category: "Alat Mandi",
    rack: 249,
  },
  { name: "Body Wash with Almond Milk", category: "Alat Mandi", rack: 250 },
  {
    name: "Facial Skin Firming Lotion with Peptides",
    category: "Alat Mandi",
    rack: 251,
  },
  {
    name: "Hair Repair Conditioner with Shea Butter",
    category: "Alat Mandi",
    rack: 252,
  },
  { name: "Body Wash with Coconut Water", category: "Alat Mandi", rack: 253 },
  {
    name: "Facial Skin Hydrating Lotion with Glycerin",
    category: "Alat Mandi",
    rack: 254,
  },
  {
    name: "Hair Nourishing Shampoo with Argan Oil",
    category: "Alat Mandi",
    rack: 255,
  },
  { name: "Body Wash with Honey Extract", category: "Alat Mandi", rack: 256 },
  {
    name: "Facial Skin Revitalizing Lotion with Vitamin E",
    category: "Alat Mandi",
    rack: 257,
  },
  {
    name: "Hair Repair Treatment with Coconut Oil",
    category: "Alat Mandi",
    rack: 258,
  },
  { name: "Body Wash with Green Tea", category: "Alat Mandi", rack: 259 },
  {
    name: "Facial Skin Nourishing Cream with Aloe Vera",
    category: "Alat Mandi",
    rack: 260,
  },
  {
    name: "Hair Moisturizing Conditioner with Jojoba Oil",
    category: "Alat Mandi",
    rack: 261,
  },
  { name: "Body Wash with Sea Salt", category: "Alat Mandi", rack: 262 },
  {
    name: "Facial Skin Soothing Lotion with Chamomile",
    category: "Alat Mandi",
    rack: 263,
  },
  {
    name: "Hair Repair Shampoo with Shea Butter",
    category: "Alat Mandi",
    rack: 264,
  },
  {
    name: "Body Wash with Charcoal Extract",
    category: "Alat Mandi",
    rack: 265,
  },
  {
    name: "Facial Skin Brightening Gel with Licorice",
    category: "Alat Mandi",
    rack: 266,
  },
  {
    name: "Hair Curling Cream with Coconut Milk",
    category: "Alat Mandi",
    rack: 267,
  },
  { name: "Body Wash with Papaya Extract", category: "Alat Mandi", rack: 268 },
  {
    name: "Facial Skin Firming Gel with Green Tea",
    category: "Alat Mandi",
    rack: 269,
  },
  {
    name: "Hair Repair Serum with Vitamin E",
    category: "Alat Mandi",
    rack: 270,
  },
  { name: "Body Wash with Avocado", category: "Alat Mandi", rack: 271 },
  {
    name: "Facial Skin Hydrating Gel with Aloe",
    category: "Alat Mandi",
    rack: 272,
  },
  {
    name: "Hair Nourishing Conditioner with Olive Oil",
    category: "Alat Mandi",
    rack: 273,
  },
  { name: "Body Wash with Coconut Cream", category: "Alat Mandi", rack: 274 },
  {
    name: "Facial Skin Revitalizing Cream with Cucumber",
    category: "Alat Mandi",
    rack: 275,
  },
  {
    name: "Hair Moisturizing Shampoo with Coconut",
    category: "Alat Mandi",
    rack: 276,
  },
  { name: "Body Wash with Mango", category: "Alat Mandi", rack: 277 },
  {
    name: "Facial Skin Brightening Lotion with Papaya",
    category: "Alat Mandi",
    rack: 278,
  },
  {
    name: "Hair Repair Treatment with Aloe Vera",
    category: "Alat Mandi",
    rack: 279,
  },
  { name: "Body Wash with Coconut Sugar", category: "Alat Mandi", rack: 280 },
  {
    name: "Facial Skin Nourishing Gel with Honey",
    category: "Alat Mandi",
    rack: 281,
  },
  { name: "Hair Curling Cream with Honey", category: "Alat Mandi", rack: 282 },
  { name: "Body Wash with Raspberry", category: "Alat Mandi", rack: 283 },
  {
    name: "Facial Skin Firming Lotion with Vitamin C",
    category: "Alat Mandi",
    rack: 284,
  },
  {
    name: "Hair Repair Conditioner with Coconut Milk",
    category: "Alat Mandi",
    rack: 285,
  },
  {
    name: "Body Wash with Blackberry Extract",
    category: "Alat Mandi",
    rack: 286,
  },
  {
    name: "Facial Skin Hydrating Cream with Rose",
    category: "Alat Mandi",
    rack: 287,
  },
  {
    name: "Hair Nourishing Shampoo with Coconut Milk",
    category: "Alat Mandi",
    rack: 288,
  },
  { name: "Body Wash with Kiwi", category: "Alat Mandi", rack: 289 },
  {
    name: "Facial Skin Revitalizing Gel with Aloe",
    category: "Alat Mandi",
    rack: 290,
  },
  {
    name: "Hair Moisturizing Conditioner with Honey",
    category: "Alat Mandi",
    rack: 291,
  },
  { name: "Body Wash with Orange", category: "Alat Mandi", rack: 292 },
  {
    name: "Facial Skin Brightening Cream with Papaya",
    category: "Alat Mandi",
    rack: 293,
  },
  {
    name: "Hair Repair Treatment with Jojoba",
    category: "Alat Mandi",
    rack: 294,
  },
  { name: "Body Wash with Lemon Zest", category: "Alat Mandi", rack: 295 },
  {
    name: "Facial Skin Nourishing Lotion with Vitamin E",
    category: "Alat Mandi",
    rack: 296,
  },
  {
    name: "Hair Curling Cream with Avocado",
    category: "Alat Mandi",
    rack: 297,
  },
  { name: "Body Wash with Coconut Lime", category: "Alat Mandi", rack: 298 },
  {
    name: "Facial Skin Firming Gel with Collagen",
    category: "Alat Mandi",
    rack: 299,
  },
  {
    name: "Hair Repair Serum with Coconut Water",
    category: "Alat Mandi",
    rack: 300,
  },
  { name: "Shower Oil", category: "Alat Mandi", rack: 301 },
  { name: "Facial Peeling Gel", category: "Alat Mandi", rack: 302 },
  { name: "Hair Repair Treatment", category: "Alat Mandi", rack: 303 },
  { name: "Body Shimmer", category: "Alat Mandi", rack: 304 },
  { name: "Nail Strengthener", category: "Alat Mandi", rack: 305 },
  { name: "Foot Peel Mask", category: "Alat Mandi", rack: 306 },
  { name: "Shower Mist", category: "Alat Mandi", rack: 307 },
  { name: "Facial Mist", category: "Alat Mandi", rack: 308 },
  { name: "Hair Frizz Control", category: "Alat Mandi", rack: 309 },
  { name: "Body Glow Oil", category: "Alat Mandi", rack: 310 },
  { name: "Exfoliating Foot Mask", category: "Alat Mandi", rack: 311 },
  { name: "Shower Jelly", category: "Alat Mandi", rack: 312 },
  { name: "Facial Exfoliator", category: "Alat Mandi", rack: 313 },
  { name: "Body Firming Cream", category: "Alat Mandi", rack: 314 },
  { name: "Hair Detangler", category: "Alat Mandi", rack: 315 },
  { name: "Bath Salts", category: "Alat Mandi", rack: 316 },
  { name: "Cooling Foot Spray", category: "Alat Mandi", rack: 317 },
  { name: "Shower Puffs", category: "Alat Mandi", rack: 318 },
  { name: "Facial Cleansing Brush", category: "Alat Mandi", rack: 319 },
  { name: "Body Shaving Gel", category: "Alat Mandi", rack: 320 },
  { name: "Hair Growth Serum", category: "Alat Mandi", rack: 321 },
  { name: "Bath Bombs", category: "Alat Mandi", rack: 322 },
  { name: "Body Shaving Cream", category: "Alat Mandi", rack: 323 },
  { name: "Facial Scrub", category: "Alat Mandi", rack: 324 },
  { name: "Hair Styling Mousse", category: "Alat Mandi", rack: 325 },
  { name: "Body Wash Foam", category: "Alat Mandi", rack: 326 },
  { name: "Shower Cream", category: "Alat Mandi", rack: 327 },
  { name: "Facial Cleansing Wipes", category: "Alat Mandi", rack: 328 },
  { name: "Body Shimmer Mist", category: "Alat Mandi", rack: 329 },
  { name: "Hair Curling Spray", category: "Alat Mandi", rack: 330 },
  { name: "Moisturizing Body Wash", category: "Alat Mandi", rack: 331 },
  { name: "Hydrating Face Mask", category: "Alat Mandi", rack: 332 },
  { name: "Nourishing Hair Oil", category: "Alat Mandi", rack: 333 },
  { name: "Body Butter", category: "Alat Mandi", rack: 334 },
  { name: "Foot Scrub Cream", category: "Alat Mandi", rack: 335 },
  { name: "Shower Gel with Aloe Vera", category: "Alat Mandi", rack: 336 },
  { name: "Facial Hydrating Mist", category: "Alat Mandi", rack: 337 },
  { name: "Hair Repair Serum", category: "Alat Mandi", rack: 338 },
  { name: "Body Wash with Charcoal", category: "Alat Mandi", rack: 339 },
  { name: "Exfoliating Body Wash", category: "Alat Mandi", rack: 340 },
  { name: "Cleansing Facial Wipes", category: "Alat Mandi", rack: 341 },
  { name: "Hair Styling Gel", category: "Alat Mandi", rack: 342 },
  { name: "Body Oil", category: "Alat Mandi", rack: 343 },
  { name: "Foot Cream with Menthol", category: "Alat Mandi", rack: 344 },
  { name: "Shower Gel with Coconut", category: "Alat Mandi", rack: 345 },
  { name: "Facial Brightening Serum", category: "Alat Mandi", rack: 346 },
  { name: "Hair Curl Definer", category: "Alat Mandi", rack: 347 },
  { name: "Body Wash with Honey", category: "Alat Mandi", rack: 348 },
  { name: "Exfoliating Facial Scrub", category: "Alat Mandi", rack: 349 },
  { name: "Hair Smoothing Cream", category: "Alat Mandi", rack: 350 },
  { name: "Body Wash with Lavender", category: "Alat Mandi", rack: 351 },
  { name: "Facial Moisturizing Cream", category: "Alat Mandi", rack: 352 },
  { name: "Hair Repair Mask", category: "Alat Mandi", rack: 353 },
  { name: "Body Wash with Tea Tree Oil", category: "Alat Mandi", rack: 354 },
  { name: "Facial Brightening Mask", category: "Alat Mandi", rack: 355 },
  { name: "Hair Volume Spray", category: "Alat Mandi", rack: 356 },
  { name: "Body Wash with Rose", category: "Alat Mandi", rack: 357 },
  { name: "Facial Firming Cream", category: "Alat Mandi", rack: 358 },
  { name: "Hair Repair Conditioner", category: "Alat Mandi", rack: 359 },
  { name: "Body Wash with Citrus", category: "Alat Mandi", rack: 360 },
  { name: "Facial Anti-Aging Serum", category: "Alat Mandi", rack: 361 },
  { name: "Hair Curl Activator", category: "Alat Mandi", rack: 362 },
  { name: "Body Wash with Mint", category: "Alat Mandi", rack: 363 },
  { name: "Facial Pore Minimizer", category: "Alat Mandi", rack: 364 },
  {
    name: "Hair Repair Leave-In Conditioner",
    category: "Alat Mandi",
    rack: 365,
  },
  { name: "Body Wash with Jasmine", category: "Alat Mandi", rack: 366 },
  { name: "Facial Oil Control Gel", category: "Alat Mandi", rack: 367 },
  { name: "Hair Frizz Control Cream", category: "Alat Mandi", rack: 368 },
  { name: "Body Wash with Olive Oil", category: "Alat Mandi", rack: 369 },
  { name: "Facial Skin Brightener", category: "Alat Mandi", rack: 370 },
  { name: "Hair Nourishing Cream", category: "Alat Mandi", rack: 371 },
  { name: "Body Wash with Almond Oil", category: "Alat Mandi", rack: 372 },
  { name: "Facial Skin Repair Cream", category: "Alat Mandi", rack: 373 },
  { name: "Hair Moisturizing Spray", category: "Alat Mandi", rack: 374 },
  { name: "Body Wash with Grapefruit", category: "Alat Mandi", rack: 375 },
  { name: "Facial Skin Soothing Gel", category: "Alat Mandi", rack: 376 },
  { name: "Hair Repair Shampoo", category: "Alat Mandi", rack: 377 },
  { name: "Body Wash with Chamomile", category: "Alat Mandi", rack: 378 },
  { name: "Facial Skin Hydrating Cream", category: "Alat Mandi", rack: 379 },
  { name: "Hair Smoothing Shampoo", category: "Alat Mandi", rack: 380 },
  { name: "Body Wash with Eucalyptus", category: "Alat Mandi", rack: 381 },
  { name: "Facial Skin Nourishing Oil", category: "Alat Mandi", rack: 382 },
  {
    name: "Hair Repair Conditioner with Argan Oil",
    category: "Alat Mandi",
    rack: 383,
  },
  { name: "Body Wash with Coconut Milk", category: "Alat Mandi", rack: 384 },
  { name: "Facial Skin Revitalizing Serum", category: "Alat Mandi", rack: 385 },
  {
    name: "Hair Repair Treatment with Keratin",
    category: "Alat Mandi",
    rack: 386,
  },
  { name: "Body Wash with Papaya", category: "Alat Mandi", rack: 387 },
  { name: "Facial Skin Rejuvenating Cream", category: "Alat Mandi", rack: 388 },
  { name: "Hair Moisturizing Conditioner", category: "Alat Mandi", rack: 389 },
  { name: "Body Wash with Pomegranate", category: "Alat Mandi", rack: 390 },
  { name: "Facial Skin Exfoliating Gel", category: "Alat Mandi", rack: 391 },
  {
    name: "Hair Repair Serum with Jojoba Oil",
    category: "Alat Mandi",
    rack: 392,
  },
  { name: "Body Wash with Cucumber", category: "Alat Mandi", rack: 393 },
  { name: "Facial Skin Brightening Lotion", category: "Alat Mandi", rack: 394 },
  {
    name: "Hair Curling Cream with Coconut",
    category: "Alat Mandi",
    rack: 395,
  },
  { name: "Body Wash with Blackberry", category: "Alat Mandi", rack: 396 },
  { name: "Facial Skin Firming Lotion", category: "Alat Mandi", rack: 397 },
  { name: "Hair Repair Mask with Avocado", category: "Alat Mandi", rack: 398 },
  { name: "Body Wash with Strawberry", category: "Alat Mandi", rack: 399 },
  { name: "Facial Skin Hydrating Lotion", category: "Alat Mandi", rack: 400 },
  { name: "Hair Nourishing Shampoo", category: "Alat Mandi", rack: 401 },
  { name: "Body Wash with Blueberry", category: "Alat Mandi", rack: 402 },
  { name: "Facial Skin Soothing Lotion", category: "Alat Mandi", rack: 403 },
  {
    name: "Hair Repair Conditioner with Coconut",
    category: "Alat Mandi",
    rack: 404,
  },
  { name: "Body Wash with Tangerine", category: "Alat Mandi", rack: 405 },
  { name: "Facial Skin Nourishing Cream", category: "Alat Mandi", rack: 406 },
  {
    name: "Hair Moisturizing Conditioner with Aloe Vera",
    category: "Alat Mandi",
    rack: 407,
  },
  { name: "Body Wash with Mint Leaf", category: "Alat Mandi", rack: 408 },
  {
    name: "Facial Skin Revitalizing Lotion",
    category: "Alat Mandi",
    rack: 409,
  },
  {
    name: "Hair Repair Shampoo with Olive Oil",
    category: "Alat Mandi",
    rack: 410,
  },
  { name: "Body Wash with Lemon", category: "Alat Mandi", rack: 411 },
  { name: "Facial Skin Anti-Aging Lotion", category: "Alat Mandi", rack: 412 },
  {
    name: "Hair Smoothing Conditioner with Shea Butter",
    category: "Alat Mandi",
    rack: 413,
  },
  { name: "Body Wash with Ginger", category: "Alat Mandi", rack: 414 },
  {
    name: "Facial Skin Rejuvenating Lotion",
    category: "Alat Mandi",
    rack: 415,
  },
  {
    name: "Hair Repair Treatment with Honey",
    category: "Alat Mandi",
    rack: 416,
  },
  { name: "Body Wash with Clove", category: "Alat Mandi", rack: 417 },
  { name: "Facial Skin Brightening Gel", category: "Alat Mandi", rack: 418 },
  { name: "Hair Curling Cream with Almond", category: "Alat Mandi", rack: 419 },
  { name: "Body Wash with Cardamom", category: "Alat Mandi", rack: 420 },
  { name: "Facial Skin Firming Gel", category: "Alat Mandi", rack: 421 },
  {
    name: "Hair Repair Serum with Coconut Milk",
    category: "Alat Mandi",
    rack: 422,
  },
  { name: "Body Wash with Basil", category: "Alat Mandi", rack: 423 },
  { name: "Facial Skin Hydrating Gel", category: "Alat Mandi", rack: 424 },
  {
    name: "Hair Nourishing Conditioner with Coconut",
    category: "Alat Mandi",
    rack: 425,
  },
  { name: "Body Wash with Rosemary", category: "Alat Mandi", rack: 426 },
  {
    name: "Facial Skin Soothing Gel with Aloe Vera",
    category: "Alat Mandi",
    rack: 427,
  },
  { name: "Hair Repair Shampoo with Honey", category: "Alat Mandi", rack: 428 },
  { name: "Body Wash with Thyme", category: "Alat Mandi", rack: 429 },
  { name: "Facial Skin Revitalizing Gel", category: "Alat Mandi", rack: 430 },
  {
    name: "Hair Moisturizing Cream with Coconut",
    category: "Alat Mandi",
    rack: 431,
  },
  { name: "Body Wash with Sage", category: "Alat Mandi", rack: 432 },
  { name: "Facial Skin Nourishing Gel", category: "Alat Mandi", rack: 433 },
  {
    name: "Hair Repair Conditioner with Honey",
    category: "Alat Mandi",
    rack: 434,
  },
  { name: "Body Wash with Mint Extract", category: "Alat Mandi", rack: 435 },
  {
    name: "Facial Skin Brightening Cream with Vitamin C",
    category: "Alat Mandi",
    rack: 436,
  },
  {
    name: "Hair Curling Gel with Aloe Vera",
    category: "Alat Mandi",
    rack: 437,
  },
  { name: "Body Wash with Lavender Oil", category: "Alat Mandi", rack: 438 },
  {
    name: "Facial Skin Firming Cream with Collagen",
    category: "Alat Mandi",
    rack: 439,
  },
  {
    name: "Hair Repair Treatment with Olive Oil",
    category: "Alat Mandi",
    rack: 440,
  },
  {
    name: "Body Wash with Chamomile Extract",
    category: "Alat Mandi",
    rack: 441,
  },
  {
    name: "Facial Skin Hydrating Cream with Hyaluronic Acid",
    category: "Alat Mandi",
    rack: 442,
  },
  {
    name: "Hair Smoothing Shampoo with Coconut Milk",
    category: "Alat Mandi",
    rack: 443,
  },
  { name: "Body Wash with Vanilla", category: "Alat Mandi", rack: 444 },
  {
    name: "Facial Skin Rejuvenating Gel with Retinol",
    category: "Alat Mandi",
    rack: 445,
  },
  {
    name: "Hair Repair Serum with Argan Oil",
    category: "Alat Mandi",
    rack: 446,
  },
  { name: "Body Wash with Coconut Oil", category: "Alat Mandi", rack: 447 },
  {
    name: "Facial Skin Brightening Lotion with Niacinamide",
    category: "Alat Mandi",
    rack: 448,
  },
  {
    name: "Hair Curling Cream with Jojoba Oil",
    category: "Alat Mandi",
    rack: 449,
  },
  { name: "Body Wash with Almond Milk", category: "Alat Mandi", rack: 450 },
  {
    name: "Facial Skin Firming Lotion with Peptides",
    category: "Alat Mandi",
    rack: 451,
  },
  {
    name: "Hair Repair Conditioner with Shea Butter",
    category: "Alat Mandi",
    rack: 452,
  },
  { name: "Body Wash with Coconut Water", category: "Alat Mandi", rack: 453 },
  {
    name: "Facial Skin Hydrating Lotion with Glycerin",
    category: "Alat Mandi",
    rack: 454,
  },
  {
    name: "Hair Nourishing Shampoo with Argan Oil",
    category: "Alat Mandi",
    rack: 455,
  },
  { name: "Body Wash with Honey Extract", category: "Alat Mandi", rack: 456 },
  {
    name: "Facial Skin Revitalizing Lotion with Vitamin E",
    category: "Alat Mandi",
    rack: 457,
  },
  {
    name: "Hair Repair Treatment with Coconut Oil",
    category: "Alat Mandi",
    rack: 458,
  },
  { name: "Body Wash with Green Tea", category: "Alat Mandi", rack: 459 },
  {
    name: "Facial Skin Nourishing Cream with Aloe Vera",
    category: "Alat Mandi",
    rack: 460,
  },
  {
    name: "Hair Moisturizing Conditioner with Jojoba Oil",
    category: "Alat Mandi",
    rack: 461,
  },
  { name: "Body Wash with Sea Salt", category: "Alat Mandi", rack: 462 },
  {
    name: "Facial Skin Soothing Lotion with Chamomile",
    category: "Alat Mandi",
    rack: 463,
  },
  {
    name: "Hair Repair Shampoo with Shea Butter",
    category: "Alat Mandi",
    rack: 464,
  },
  {
    name: "Body Wash with Charcoal Extract",
    category: "Alat Mandi",
    rack: 465,
  },
  {
    name: "Facial Skin Brightening Gel with Licorice",
    category: "Alat Mandi",
    rack: 466,
  },
  {
    name: "Hair Curling Cream with Coconut Milk",
    category: "Alat Mandi",
    rack: 467,
  },
  { name: "Body Wash with Papaya Extract", category: "Alat Mandi", rack: 468 },
  {
    name: "Facial Skin Firming Gel with Green Tea",
    category: "Alat Mandi",
    rack: 469,
  },
  {
    name: "Hair Repair Serum with Vitamin E",
    category: "Alat Mandi",
    rack: 470,
  },
  { name: "Body Wash with Avocado", category: "Alat Mandi", rack: 471 },
  {
    name: "Facial Skin Hydrating Gel with Aloe",
    category: "Alat Mandi",
    rack: 472,
  },
  {
    name: "Hair Nourishing Conditioner with Olive Oil",
    category: "Alat Mandi",
    rack: 473,
  },
  { name: "Body Wash with Coconut Cream", category: "Alat Mandi", rack: 474 },
  {
    name: "Facial Skin Revitalizing Cream with Cucumber",
    category: "Alat Mandi",
    rack: 475,
  },
  {
    name: "Hair Moisturizing Shampoo with Coconut",
    category: "Alat Mandi",
    rack: 476,
  },
  { name: "Body Wash with Mango", category: "Alat Mandi", rack: 477 },
  {
    name: "Facial Skin Brightening Lotion with Papaya",
    category: "Alat Mandi",
    rack: 478,
  },
  {
    name: "Hair Repair Treatment with Aloe Vera",
    category: "Alat Mandi",
    rack: 479,
  },
  { name: "Body Wash with Coconut Sugar", category: "Alat Mandi", rack: 480 },
  {
    name: "Facial Skin Nourishing Gel with Honey",
    category: "Alat Mandi",
    rack: 481,
  },
  { name: "Hair Curling Cream with Honey", category: "Alat Mandi", rack: 482 },
  { name: "Body Wash with Raspberry", category: "Alat Mandi", rack: 483 },
  {
    name: "Facial Skin Firming Lotion with Vitamin C",
    category: "Alat Mandi",
    rack: 484,
  },
  {
    name: "Hair Repair Conditioner with Coconut Milk",
    category: "Alat Mandi",
    rack: 485,
  },
  {
    name: "Body Wash with Blackberry Extract",
    category: "Alat Mandi",
    rack: 486,
  },
  {
    name: "Facial Skin Hydrating Cream with Rose",
    category: "Alat Mandi",
    rack: 487,
  },
  {
    name: "Hair Nourishing Shampoo with Coconut Milk",
    category: "Alat Mandi",
    rack: 488,
  },
  { name: "Body Wash with Kiwi", category: "Alat Mandi", rack: 489 },
  {
    name: "Facial Skin Revitalizing Gel with Aloe",
    category: "Alat Mandi",
    rack: 490,
  },
  {
    name: "Hair Moisturizing Conditioner with Honey",
    category: "Alat Mandi",
    rack: 491,
  },
  { name: "Body Wash with Orange", category: "Alat Mandi", rack: 492 },
  {
    name: "Facial Skin Brightening Cream with Papaya",
    category: "Alat Mandi",
    rack: 493,
  },
  {
    name: "Hair Repair Treatment with Jojoba",
    category: "Alat Mandi",
    rack: 494,
  },
  { name: "Body Wash with Lemon Zest", category: "Alat Mandi", rack: 495 },
  {
    name: "Facial Skin Nourishing Lotion with Vitamin E",
    category: "Alat Mandi",
    rack: 496,
  },
  {
    name: "Hair Curling Cream with Avocado",
    category: "Alat Mandi",
    rack: 497,
  },
  { name: "Body Wash with Coconut Lime", category: "Alat Mandi", rack: 498 },
  {
    name: "Facial Skin Firming Gel with Collagen",
    category: "Alat Mandi",
    rack: 499,
  },
  {
    name: "Hair Repair Serum with Coconut Water",
    category: "Alat Mandi",
    rack: 500,
  },
];
// Menyaring produk berdasarkan kategori yang dipilih
function filterProducts() {
  const category = document.getElementById("category").value; // Ambil kategori yang dipilih

  // Filter produk berdasarkan kategori
  const filteredProducts = products.filter(
    (product) => product.category === category
  );

  // Tampilkan produk yang sudah difilter
  displayProducts(filteredProducts);
}

// Fungsi untuk memilih dan menjalankan metode sorting serta mengukur waktu / running timenya
function sortProducts() {
  const category = document.getElementById("category").value; // Ambil kategori yang dipilih
  const filteredProducts = products.filter(
    (product) => product.category === category
  ); // Filter produk berdasarkan kategori yang dipilih

  const method = document.getElementById("sortingMethod").value; // Ambil metode sorting yang dipilih
  const startTime = performance.now(); // Mulai pengukuran waktu

  // Panggil metode sorting yang sesuai
  if (method === "iterative") {
    bubbleSortIterative(filteredProducts); // Sorting iteratif berdasarkan kategori
  } else if (method === "recursive") {
    bubbleSortRecursive(filteredProducts); // Sorting rekursif berdasarkan kategori
  }

  const endTime = performance.now(); // Selesai pengukuran waktu
  const timeTaken = (endTime - startTime).toFixed(4); // Waktu dalam milidetik

  displayProducts(filteredProducts); // Tampilkan produk yang sudah disortir
  displayTime(timeTaken); // Tampilkan waktu eksekusi
}

// Algoritma Bubble Sort Iteratif
function bubbleSortIterative(array) {
  let n = array.length;
  for (let i = 0; i < n - 1; i++) {
    for (let j = 0; j < n - i - 1; j++) {
      if (
        array[j].name > array[j + 1].name // Sorting berdasarkan nama produk
      ) {
        [array[j], array[j + 1]] = [array[j + 1], array[j]]; // Tukar posisi jika urutannya salah
      }
    }
  }
}

// Algoritma Bubble Sort Rekursif
function bubbleSortRecursive(array, n = array.length) {
  if (n === 1) return; // Basis rekursi: jika panjang array sudah 1, selesai

  for (let i = 0; i < n - 1; i++) {
    if (
      array[i].name > array[i + 1].name // Sorting berdasarkan nama produk
    ) {
      [array[i], array[i + 1]] = [array[i + 1], array[i]]; // Tukar posisi jika urutannya salah
    }
  }

  bubbleSortRecursive(array, n - 1); // Panggil rekursif untuk sisa array
}

// Fungsi untuk menampilkan running timeny
function displayTime(timeTaken) {
  const timeDisplay = document.getElementById("timeDisplay");
  timeDisplay.textContent = `Waktu eksekusi: ${timeTaken} milidetik`;
}

// Fungsi untuk menampilkan produk yang sudah disortir
function displayProducts(filteredProducts) {
  const tbody = document.querySelector("#productTable tbody");
  tbody.innerHTML = ""; // Hapus konten sebelumnya

  filteredProducts.forEach((product) => {
    const row = document.createElement("tr");
    row.innerHTML = `
        <td>${product.name}</td>
        <td>${product.category}</td>
        <td>${product.rack}</td>
      `;
    tbody.appendChild(row);
  });
}

// Tampilkan data awal saat halaman dimuat
displayProducts(products);
